# Generated by Django 4.2.17 on 2025-02-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_timeslot_options_court_address_court_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinggroup',
            options={'verbose_name': 'Nhóm booking', 'verbose_name_plural': 'Nhóm booking'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Sân', 'verbose_name_plural': 'Sân'},
        ),
        migrations.AlterModelOptions(
            name='courtbankaccount',
            options={'verbose_name': 'Tài khoản ngân hàng', 'verbose_name_plural': 'Tài khoản ngân hàng'},
        ),
        migrations.AlterModelOptions(
            name='courttimeslot',
            options={'verbose_name': 'Sân - Khung giờ', 'verbose_name_plural': 'Sân - Khung giờ'},
        ),
        migrations.AlterModelOptions(
            name='fixedschedule',
            options={'verbose_name': 'Cố định', 'verbose_name_plural': 'Cố định'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Khung giờ', 'verbose_name_plural': 'Khung giờ'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_book_court', 'Can book court'), ('can_manage_court', 'Can manage court'), ('can_manage_system', 'Can manage system'), ('can_check_in', 'Can check in customers')], 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterField(
            model_name='fixedschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')]),
        ),
    ]
