# Generated by Django 4.2.17 on 2025-02-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bookinggroup_options_alter_court_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinggroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courtbankaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courttimeslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fixedschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_book_court', 'Can book court'), ('can_manage_court', 'Can manage court'), ('can_manage_system', 'Can manage system'), ('can_check_in', 'Can check in customers')]},
        ),
    ]
